---
  - name: Enable epel-release
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      state: present
    register: result

  - name: Import EPEL GPG key.
    rpm_key:
      key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
      state: present

  # - name: Add repository
  #   yum_repository:
  #     name: epel
  #     description: EPEL YUM repo
  #     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  - name: Install default packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages }}"
    # ignore_errors: yes

  - name: Disable SElinux
    selinux:
      state: disabled
