---

  - name: Remove Any Previous Versions of Java
    yum:
      name: java-1.7.0-openjdk
      state: absent

  - name: Install Java Version 8
    yum:
      name: java-1.8.0-openjdk

  - name: Install Elasticsearch Repository
    yum_repository:
      name: elasticsearch
      description: Elasticsearch repository for 6.x packages
      baseurl: https://artifacts.elastic.co/packages/6.x/yum
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      gpgcheck: yes
      enabled: yes

  - name: Update YUM Packages List
    yum:
      name: '*'
      state: latest

  - name: Install Elasticsearch (latest 6 version available)
    yum:
      name: elasticsearch
      state: latest

#  - name: Set Elasticsearch Configuration File
#    template:
#      src: elasticsearch.yml.j2
#      dest: /etc/elasticsearch/elasticsearch.yml

  - name: Start Elasticsearch service
    service:
      name: elasticsearch
      state: started
  #    wait_for: port=9200 delay=5

      #  - name: Check Cluster Health
      # uri:
      # url: http://{{ansible_ssh_host}}:9200/_cluster/health?pretty
      #method: GET
      # return_content: yes
      # retries: 5
      #delay: 15
