---

  - name: Install Kibana (latest 6 version available)
    yum:
      name: kibana
      state: latest

  - name: Set Kibana Configuration File
    template:
      src: kibana.yml.j2
      dest: /etc/kibana/kibana.yml

  - name: Start Kibana service
    service:
      name: kibana
      state: started
    #  wait_for: port=5601 delay=5
